import canonicalLaneMathlib.AdmissibleClass

namespace HautevilleHouse
namespace FourierFourierStieltjesTransformsLocallyCanonicalLaneLean

end FourierFourierStieltjesTransformsLocallyCanonicalLaneLean
end HautevilleHouse
